### ISSUE TITLE
Was ist der Ausbauplan für dieses Repository

### ISSUE THREAD

**Issue by RESDE** [TA2k/ioBroker.vaillant#1]
Lieber GIT Kollege,

was ist der Ausbaulan für diesen Adapter. Die Kurzbeschreibung lässt ja einiges hoffen...
Aktuell suche ich nicht nur einen coolen Adapter in IObroker sondern am besten auch Interessierte, die sich eine gute Heizungs-VIS bauen wollen, um wirklich Kontrolle der Vaillant Heizung zu haben.
Wird der Adapter die TCP Daten abfangen und in IORboker Objekte direkt übernehmen? Oder muss noch ein Ebus Adpater angeschafft werden (Dazu gibt es ja schon Projekbeispiele, dachte aber das das geht doch schöner und schneller via IOBRoker und Adapter
Vielen Dank für Deinen Support

**Comment by TA2k** [comment]
Ich werde den Adapter heute abend anfangen da wird es dann auch ein lesend version geben.
Bisher ist es nur geplant multimatic VR900/920 zu unterstützen. Das heißt ebus + vr modul.

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/29221/test-adapter-vaillant-multimatic-v0-0-1
