### ISSUE TITLE
Get a lot of errors and warnings

### ISSUE THREAD

**Issue by ServerFE** [TA2k/ioBroker.vaillant#10]
vaillant.0 | 2021-01-17 21:41:40.533 | warn | (27663) State "vaillant.0.xxx.systemcontrol.dhw01.circulation.configuration.operationMode" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
vaillant.0 | 2021-01-17 21:41:40.529 | warn | (27663) State "vaillant.0.xxx.systemcontrol.dhw01.hotwater.configuration.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.529 | warn | (27663) State "vaillant.0.xxx.systemcontrol.dhw01.hotwater.configuration.operation_mode" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.526 | warn | (27663) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.526 | warn | (27663) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.end_date" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.526 | warn | (27663) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.start_date" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.526 | warn | (27663) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.active" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.525 | warn | (27663) State "vaillant.0.XXX.systemcontrol.configuration.eco_mode" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.525 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.configuration.quick_veto.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.525 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.configuration.quick_veto.active" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.525 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.configuration.active_function" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.525 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.configuration.enabled" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.524 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.configuration.name" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.523 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.heating.configuration.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.522 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.heating.configuration.setback_temperature" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:41:40.522 | warn | (27663) State "vaillant.0.XXX.systemcontrol.zones01.heating.configuration.mode" has no existing object, this might lead to an error in future versions
unifi.0 | 2021-01-17 21:41:35.618 | info | (27402) Update done
vaillant.0 | 2021-01-17 21:41:29.379 | info | (27663) Generate new Id
vaillant.0 | 2021-01-17 21:41:29.363 | info | (27663) starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.vaillant, node: v12.20.1, js-controller: 3.2.7
host.ioBroker | 2021-01-17 21:41:28.803 | info | instance system.adapter.vaillant.0 started with pid 27663
host.ioBroker | 2021-01-17 21:40:58.792 | info | Restart adapter system.adapter.vaillant.0 because enabled
host.ioBroker | 2021-01-17 21:40:58.790 | error | instance system.adapter.vaillant.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
vaillant.0 | 2021-01-17 21:40:58.236 | warn | (27648) Terminated (UNCAUGHT_EXCEPTION): Without reason
vaillant.0 | 2021-01-17 21:40:58.236 | info | (27648) terminating
vaillant.0 | 2021-01-17 21:40:58.235 | info | (27648) cleaned everything up...
vaillant.0 | 2021-01-17 21:40:58.230 | error | (27648) The state contains no properties! At least one property is expected!
vaillant.0 | 2021-01-17 21:40:58.230 | error | (27648) Error: The state contains no properties! At least one property is expected! at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5783:23)
vaillant.0 | 2021-01-17 21:40:58.229 | error | (27648) unhandled promise rejection: The state contains no properties! At least one property is expected!
vaillant.0 | 2021-01-17 21:40:58.229 | error | (27648) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
vaillant.0 | 2021-01-17 21:40:38.078 | warn | (27648) State "vaillant.0.XXX.systemcontrol.dhw01.circulation.configuration.operationMode" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.074 | warn | (27648) State "vaillant.0.XXX.systemcontrol.dhw01.hotwater.configuration.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.074 | warn | (27648) State "vaillant.0.XXX.systemcontrol.dhw01.hotwater.configuration.operation_mode" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.071 | warn | (27648) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.071 | warn | (27648) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.end_date" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.071 | warn | (27648) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.start_date" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.070 | warn | (27648) State "vaillant.0.XXX.systemcontrol.configuration.holidaymode.active" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.070 | warn | (27648) State "vaillant.0.XXX.systemcontrol.configuration.eco_mode" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.070 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.configuration.quick_veto.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.070 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.configuration.quick_veto.active" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.070 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.configuration.active_function" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.069 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.configuration.enabled" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.069 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.configuration.name" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.068 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.heating.configuration.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.067 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.heating.configuration.setback_temperature" has no existing object, this might lead to an error in future versions
vaillant.0 | 2021-01-17 21:40:38.067 | warn | (27648) State "vaillant.0.XXX.systemcontrol.zones01.heating.configuration.mode" has no existing object, this might lead to an error in future versions

 Adapter Version: 0.0.10
IoBroker Version: 3.2.7
NodeJS Version: 12.20.1
NPM Version: 6.14.10

**Comment by sbeier23** [comment]
It just crashes with a restart loop in my case:

`vaillant.0	2021-01-18 07:50:17.021	warn	(9320) Terminated (UNCAUGHT_EXCEPTION): Without reason
vaillant.0	2021-01-18 07:50:17.021	info	(9320) terminating
vaillant.0	2021-01-18 07:50:17.020	info	(9320) cleaned everything up...
vaillant.0	2021-01-18 07:50:17.015	error	(9320) The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:50:17.014	error	at Traverse.forEach (/opt/iobroker/node_modules/traverse/index.js:50:18)
vaillant.0	2021-01-18 07:50:17.014	error	at walk (/opt/iobroker/node_modules/traverse/index.js:226:7)
vaillant.0	2021-01-18 07:50:17.014	error	at walker (/opt/iobroker/node_modules/traverse/index.js:203:13)
vaillant.0	2021-01-18 07:50:17.014	error	at forEach (/opt/iobroker/node_modules/traverse/index.js:298:31)
vaillant.0	2021-01-18 07:50:17.014	error	at Array.forEach (<anonymous>)
vaillant.0	2021-01-18 07:50:17.014	error	at /opt/iobroker/node_modules/traverse/index.js:208:29
vaillant.0	2021-01-18 07:50:17.014	error	at walker (/opt/iobroker/node_modules/traverse/index.js:190:22)
vaillant.0	2021-01-18 07:50:17.014	error	at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.vaillant/main.js:459:41)
vaillant.0	2021-01-18 07:50:17.014	error	at Vaillant.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5897:21)
vaillant.0	2021-01-18 07:50:17.014	error	at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5783:23)
vaillant.0	2021-01-18 07:50:17.014	error	(9320) Error: The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:50:17.013	error	(9320) unhandled promise rejection: The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:50:17.013	error	(9320) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
vaillant.0	2021-01-18 07:49:56.696	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.circulation.configuration.operationMode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.692	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.hotwater.configuration.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.691	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.hotwater.configuration.operation_mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.678	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.677	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.end_date" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.677	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.start_date" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.677	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.active" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.677	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.eco_mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.676	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.quick_veto.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.676	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.quick_veto.active" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.676	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.inside_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.675	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.active_function" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.675	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.enabled" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.675	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.name" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.670	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.669	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.setback_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:56.669	warn	(9320) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:49:45.664	info	(9320) Generate new Id
vaillant.0	2021-01-18 07:49:45.644	info	(9320) starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.vaillant, node: v12.20.1, js-controller: 3.2.7
vaillant.0	2021-01-18 07:49:14.482	warn	(8598) Terminated (UNCAUGHT_EXCEPTION): Without reason
vaillant.0	2021-01-18 07:49:14.482	info	(8598) terminating
vaillant.0	2021-01-18 07:49:14.481	info	(8598) cleaned everything up...
vaillant.0	2021-01-18 07:49:14.476	error	(8598) The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:49:14.476	error	at Traverse.forEach (/opt/iobroker/node_modules/traverse/index.js:50:18)
vaillant.0	2021-01-18 07:49:14.476	error	at walk (/opt/iobroker/node_modules/traverse/index.js:226:7)
vaillant.0	2021-01-18 07:49:14.476	error	at walker (/opt/iobroker/node_modules/traverse/index.js:203:13)
vaillant.0	2021-01-18 07:49:14.476	error	at forEach (/opt/iobroker/node_modules/traverse/index.js:298:31)
vaillant.0	2021-01-18 07:49:14.476	error	at Array.forEach (<anonymous>)
vaillant.0	2021-01-18 07:49:14.476	error	at /opt/iobroker/node_modules/traverse/index.js:208:29
vaillant.0	2021-01-18 07:49:14.476	error	at walker (/opt/iobroker/node_modules/traverse/index.js:190:22)
vaillant.0	2021-01-18 07:49:14.476	error	at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.vaillant/main.js:459:41)
vaillant.0	2021-01-18 07:49:14.476	error	at Vaillant.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5897:21)
vaillant.0	2021-01-18 07:49:14.476	error	at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5783:23)
vaillant.0	2021-01-18 07:49:14.476	error	(8598) Error: The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:49:14.475	error	(8598) unhandled promise rejection: The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:49:14.475	error	(8598) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
vaillant.0	2021-01-18 07:48:54.372	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.circulation.configuration.operationMode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.363	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.hotwater.configuration.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.363	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.hotwater.configuration.operation_mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.350	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.350	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.end_date" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.350	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.start_date" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.349	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.active" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.349	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.eco_mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.349	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.quick_veto.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.348	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.quick_veto.active" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.348	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.inside_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.348	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.active_function" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.348	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.enabled" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.347	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.name" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.342	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.342	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.setback_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:54.341	warn	(8598) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:48:43.357	info	(8598) Generate new Id
vaillant.0	2021-01-18 07:48:43.334	info	(8598) starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.vaillant, node: v12.20.1, js-controller: 3.2.7
vaillant.0	2021-01-18 07:48:12.102	warn	(7814) Terminated (UNCAUGHT_EXCEPTION): Without reason
vaillant.0	2021-01-18 07:48:12.102	info	(7814) terminating
vaillant.0	2021-01-18 07:48:12.101	info	(7814) cleaned everything up...
vaillant.0	2021-01-18 07:48:12.068	error	(7814) The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:48:12.068	error	at Traverse.forEach (/opt/iobroker/node_modules/traverse/index.js:50:18)
vaillant.0	2021-01-18 07:48:12.068	error	at walk (/opt/iobroker/node_modules/traverse/index.js:226:7)
vaillant.0	2021-01-18 07:48:12.068	error	at walker (/opt/iobroker/node_modules/traverse/index.js:203:13)
vaillant.0	2021-01-18 07:48:12.068	error	at forEach (/opt/iobroker/node_modules/traverse/index.js:298:31)
vaillant.0	2021-01-18 07:48:12.068	error	at Array.forEach (<anonymous>)
vaillant.0	2021-01-18 07:48:12.068	error	at /opt/iobroker/node_modules/traverse/index.js:208:29
vaillant.0	2021-01-18 07:48:12.068	error	at walker (/opt/iobroker/node_modules/traverse/index.js:190:22)
vaillant.0	2021-01-18 07:48:12.068	error	at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.vaillant/main.js:459:41)
vaillant.0	2021-01-18 07:48:12.068	error	at Vaillant.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5897:21)
vaillant.0	2021-01-18 07:48:12.068	error	at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5783:23)
vaillant.0	2021-01-18 07:48:12.068	error	(7814) Error: The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:48:12.067	error	(7814) unhandled promise rejection: The state contains no properties! At least one property is expected!
vaillant.0	2021-01-18 07:48:12.067	error	(7814) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
vaillant.0	2021-01-18 07:47:51.975	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.circulation.configuration.operationMode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.970	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.hotwater.configuration.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.969	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.dhw01.hotwater.configuration.operation_mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.956	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.temperature_setpoint" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.956	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.end_date" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.956	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.start_date" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.955	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.holidaymode.active" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.955	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.configuration.eco_mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.955	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.quick_veto.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.954	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.quick_veto.active" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.954	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.inside_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.954	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.active_function" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.954	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.enabled" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.953	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.configuration.name" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.948	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.setpoint_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.948	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.setback_temperature" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:51.947	warn	(7814) State "vaillant.0.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.systemcontrol.zones01.heating.configuration.mode" has no existing object, this might lead to an error in future versions
vaillant.0	2021-01-18 07:47:40.827	info	(7814) Generate new Id
vaillant.0	2021-01-18 07:47:40.800	info	(7814) starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.vaillant, node: v12.20.1, js-controller: 3.2.7`

**Comment by ServerFE** [comment]
Same at my side. 
Crashes with a restart loop.

Seems that there is a timing Problem. The Values gets in in the second when the adapter is restarting. 
Then the adapter restarts, the values deleted by the restart routine and same problem. 

Maybe a timeout in the script would help?

**Comment by ServerFE** [comment]
I installed the adapter with the github URL. Now my adapter works=)
See the solution at the end of this thread. 
https://forum.iobroker.net/topic/29221/test-adapter-vaillant-multimatic-v0-0-x/196?lang=de
