### ISSUE TITLE
Ambisense Ventile werden nicht gefunden

### ISSUE THREAD

**Issue by mamsis** [TA2k/ioBroker.vaillant#11]
Ich habe die Vaillant Heizung mit V920 Adapter. 
Ich habe alle Heizkörper einzeln geregelt mit den Ambisense-Ventilen von Vaillant. Über den Vaillant-Adapter  kann ich die Heizung nicht wirklich steuern, da die Datenpunkte der Ventile fehlen. Kannst DU diese integrieren? Das wäre super...

**Comment by TA2k** [comment]
Melde dich bitte mal via iobroker forum
https://forum.iobroker.net/user/tombox
