### ISSUE TITLE
Adpeter stürzt ab und läuft in die Restart-Loop detection

### ISSUE THREAD

**Issue by einhinz** [TA2k/ioBroker.vaillant#25]
Hallo,

Seit gestern Nachmittag lässt sich der Adapter nicht mehr starten. Hab schon die Instanz gelöscht und neu angelegt. Da hat es zwischendurch mal funktioniert. Dann wieder nicht nach einem weiteren Adapterneustart. Laufe ich hier in ein Blocking von Vaillant und muss nur geduldig sein, oder hat aktuell auch jemand anderes das Problem?

<html><body>

vaillant.0 | 2022-11-20 07:52:18.191 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
vaillant.0 | 2022-11-20 07:52:18.189 | info | terminating
vaillant.0 | 2022-11-20 07:52:18.187 | info | cleaned everything up...
vaillant.0 | 2022-11-20 07:52:18.160 | error | Cannot read property 'statusCode' of undefined
vaillant.0 | 2022-11-20 07:52:18.159 | error | TypeError: Cannot read property 'statusCode' of undefined     at Request._callback (/opt/iobroker/node_modules/iobroker.vaillant/main.js:230:33)     at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)     at Request.emit (events.js:315:20)     at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)     at ClientRequest.emit (events.js:315:20)     at TLSSocket.socketErrorListener (_http_client.js:469:9)     at TLSSocket.emit (events.js:315:20)     at emitErrorNT (internal/streams/destroy.js:106:8)     at emitErrorCloseNT (internal/streams/destroy.js:74:3)     at processTicksAndRejections (internal/process/task_queues.js:80:21)
vaillant.0 | 2022-11-20 07:52:18.155 | error | uncaught exception: Cannot read property 'statusCode' of undefined
vaillant.0 | 2022-11-20 07:52:18.152 | error | undefined
vaillant.0 | 2022-11-20 07:52:18.151 | error | Error: read ECONNRESET
vaillant.0 | 2022-11-20 07:52:18.150 | error | Failed to login
vaillant.0 | 2022-11-20 07:52:17.671 | info | Generate new Id
vaillant.0 | 2022-11-20 07:52:17.582 | info | starting. Version 0.0.17 in /opt/iobroker/node_modules/iobroker.vaillant, node: v14.16.0, js-controller: 4.0.19

</body>
</html>

**Comment by TA2k** [comment]
habe ich mit 0.0.18 behoben
