### ISSUE TITLE
Neues Anmeldeverfahren bei Vaillant

### ISSUE THREAD

**Issue by chrispi68** [TA2k/ioBroker.vaillant#29]
Seit Vorgestern empfängt mein Adapter keine Daten mehr. Bei der Prüfung mit der MyVaillant-App habe ich festgestellt, dass ein Zwangsupdate erforderlich ist. Nach Installation wurde ich auf ein neues Anmeldeverfahren hingewiesen. Ich habe zwangsweise umgestellt. Danach funktioniert der Adapter weiterhin nicht, auch nicht mit den neuen Logindaten, die ich bei der Umstellung angeben musste.

Log:

`{"errorCode":"E0000004","errorSummary":"Authentifizierung fehlgeschlagen","errorLink":"E0000004","errorId":"oaesT7WEIJ9RimbSwZsENcFtA","errorCauses":[]}`

**Comment by TA2k** [comment]
Ich bräuchte so ein Account um zu sehen was da anders ist 
tombox2020@gmail.com

**Comment by chrispi68** [comment]
Habe ich per Mail zugesendet. Anbei noch ein Screenshot zu den Änderungen der neuen App.

![IMG_1216](https://user-images.githubusercontent.com/33786075/222550559-df5a6504-3e6c-439f-a782-0e3e15080f70.jpeg)

**Comment by TA2k** [comment]
Bitte mal die GitHub version testen ob es wieder geht.

**Comment by chrispi68** [comment]
Scheint noch nicht zu funktionieren. Version: Version 0.1.1 heute um ca. 8:00 Uhr aus GitHub.

<img width="1296" alt="Bildschirm­foto 2023-03-03 um 08 11 44" src="https://user-images.githubusercontent.com/33786075/222655212-03ea4701-bb27-4835-9c3b-85354e854d87.png">

**Comment by TA2k** [comment]
nochmal installieren habe die logs verbessert

**Comment by chrispi68** [comment]
Anbei das Log-File. Benutzername und Passwort habe ich dreimal geprüft und sie sollten stimmen.

<img width="1180" alt="Bildschirm­foto 2023-03-03 um 08 51 30" src="https://user-images.githubusercontent.com/33786075/222662766-7975a493-2c63-4755-885c-d7bc683cc1f1.png">

**Comment by TA2k** [comment]
sollte jetzt gehen

**Comment by chrispi68** [comment]
Funktioniert wieder. Viele Dank für die schnelle Hilfe!

**Comment by kaese2002** [comment]
Hallo

Das funktioniert anscheinend nur, wenn man die MyVaillant App schon nutzt...Meine Heizung ist aber noch nicht umgestellt. Ich bekomme auch mit der 0.1.1 immer noch Login Failed...
Nutzt die Multimatic app

**Comment by chrispi68** [comment]
> Das funktioniert anscheinend nur, wenn man die MyVaillant App schon nutzt...Meine Heizung ist aber noch nicht umgestellt.

Warum hast Du noch nicht umgestellt?

**Comment by kaese2002** [comment]
Das entscheide ja nicht ich, sondern Vaillant. Meine Ecocompact is erst in Q2 oder Q3 2023 dran...
Gibt noch keinen Code in der App

**Comment by chrispi68** [comment]
> Das entscheide ja nicht ich, sondern Vaillant. Meine Ecocompact is erst in Q2 oder Q3 2023 dran...
> Gibt noch keinen Code in der App

Ok, danke. Das wusste ich nicht.

**Comment by maximilianlembke** [comment]
Steht hier eine Lösung für das Anmeldeproblem die ich überlesen habe? 

- Nutzerdaten sind zu 100% richtig. 
- Umstellung auf myVaillant war vor einigen Monaten. 

Aber leider ist das anmelden über das Adapter nicht möglich.

<img width="1025" alt="Bildschirmfoto 2023-08-22 um 22 06 11" src="https://github.com/TA2k/ioBroker.vaillant/assets/38457891/11599a75-4193-4f07-8e3f-c025bbc0c260">

**Comment by TA2k** [comment]
Brauch ich die Zugangsdaten um das nachzuvollziehen
tombox2020@gmail.com
