### ISSUE TITLE
Adapter läuft stabil aber keine Werte in den states enthalten

### ISSUE THREAD

**Issue by RESDE** [TA2k/ioBroker.vaillant#3]
Hallo Entwickler,

so jetzt läuft der Adapter seit 2 Tagen szabil und ohne Abbrüche. Super Danke.
Aber die States beinhalten kein Steuerungswerte für Temperaturen. Lediglich betriebsstati wie Heizung an,aus oder Betiebsmodi. Können Sie hier nochmals bei der Fehlersuche helfen.
Ich habe mal den Objektbaum als JSOn exportiert. Würde der bei der Fehlranalyse schneller helfen?

Zusätzlich sind einige Unterkategorien jeweils doppelt enthalten, jedoch jeweils eine davon ist immer leer. Können diese Redundanzen eliminiert werden durch Änderungend es Adapters?

Sollten die wirklich inneren Steuerungswerte ebenfalls in den states abgegriffen werden (Vorlauftemperatur, Reglerstellungen, Werte der Außenlüfterinheit, eben alles was in den Fachhanderwerker Einstellungen unter Systemaktoren test alles abgelesen werden kann?
Hier mal ein auszug der wesentlichen Paramter, die an der Heizung ablesbar sind:
Hier meine Einstellungen:

Wasserdruck 2.0Bar
Systemstatus Standby
Frostschutzverzög. 4 h
AT Durchheizen -12C
adaptive Heizkurve Nein
Betr. artwirkung konf. Alle
Autom. Kühlung Nein
AT Kühlen starten 21C
Quellenregenierung Nein
Hybridmanager Bivalenzp.
Bivalenzpunkt Heizung -7C
Bivalenzpunkt WW -7C
Alternativpunkt aus
Temp. Notbetrieb 25C
Typ Zusatzheizgerät Brennwert
Energieversorger WP aus
Zusatzheizgerät inaktiv
System Vorlauftemp. 32C
PV Puffersp. Offset 10K
Systemschema 8
Konfig VR71 3
MA VR70 , Adr.1 ohne Funkt.
Mulifunktionsausg. 2 Zirkul.p.
Ausg. Zusatzheizg. 3
Mulifunktionseing. 1x Zirklul.
Status standby
akt. Vorlauftemp. 34C
Kreisart Heizen
Status Heizbetr.
Vorlaufsolltemp. HK1 32C / HK2 29C
Isttemperatur HK1 32C / HK2 29C
Temperaturpberhöh. 0K
AT-Abschaltgrenze 21C
Minimaltemperatur 15C
Maximaltemperatur 45C
Modus Auto Off Eco
Heizkurve HK1 0,3 / HK2 0,2
Raumaufschaltung keine
Kühlen möglich ja
Taupunktüberw. ja
AT Kühlen beenden 4C
Offset Taupunkt 2C
Status ext. Wärmebed an
Pumpenstatus HK1 aus / HK2 an
Mischerstatus schließt
Tagtemp. 21C
Nachttemp. 21C
Zonenzuordnung VRC700
Status Zonenventil zu
warmwasserkreis Speicher aktiv
Vorlaufsolltemp. 0C
Speicheristtemp. 57C
Warmwasser 50C
Speicherladepumpe aus
Zirkulationspumpe an
Legionellenschutz Tag aus
Legionellen Schutz Zeit 04:00
Hysterese Speicherl. 5K
Speicherlad. Offset 5K
Max. Speicherladez. 60min.
Sperrzeit WW-Bedarf 60min.
Paral. Speicherl. aus
Speichertemp., oben 29C
Speichertemp., unten 29C

Dann spezielle Untermenues liefern:
Kompressor Std. 545h
Kompressor Starts 1383
Gebäudepumpe Std. 1646
Gebäudepumpe Starts 297
Umweltpumpe Std. 608
Umweltpumpe Starts 1414
Lüfter1 Std 667
Lüfter1 Starts 1839
Enteiser1 Std 0
Enteiser1 Schaltv. 77
EEV Schritte 282733
EEV-VI Schritte 391184
Schaltv. VUV Warmw. 304
Stromv. Heizstab ges. 1887kwh (denke durch vertauschte Sole + Estrichprogramm)
Betriebsstunden Heizstab 343
Schaltv. Heizstab 354

Fachhandwerker - Konfiguration
Kompressorstart ab -60°min
Max. Rücklauftemperatur 70°
Komp. Hysterese 7K
max. Restförderhöhe 1100mbar
Konf.Gebäudep.Heiz Auto
Konf.Gebäudep.WW Auto
Resetperrzeit 0min
Leistungsgr.Heizst. 2kW
Umweltpumpe Sollwert 61%
Konf. Lüfter Auto
Flüsterbetrieb Lüfter 25%
Einfrierschutz -28° 
die jeweiligen Werte sind nicht meine tatsächlichen, die würde ich ja gerne mit dem Adapter auslesen... :-)
Hoffe das ist O.K. wenn ich gewisse Hoffnung in diese Adapter hege,....

Grüsse

**Comment by TA2k** [comment]
Das Problem ist der Adapter liest nur die Werte aus der Vaillant mulitmatic Smartphone App aus.
Es ist nicht vergleich mit dem was was man per ebus oder an der Anlage direkt bekommt.
Wenn du Werte in der App findest die nicht im Adapter sind kann ich die gerne noch einfügen.
Auch das Entfernen von Duplikate ist relativ aufwendig, es wird eher ungefiltert wiedergeben was die App ausgibt.
