### ISSUE TITLE
Fehler nach wechsel von SensoNet App auf myVaillant App

### ISSUE THREAD

**Issue by JoeKN82** [TA2k/ioBroker.vaillant#43]
Hallo, 
da seit einigen Tagen die SensoNet App mich immer dazu aufgefordert hat zu myVaillant zu wechseln habe ich das heute gemacht. Ich besitze eine sensoNET VR 921 und eine vwf117/4 Wärmepumpe. Beim Update hat es auch eine neue Software für das Internetmodul installiert. In der myVailland app funktioniert alles wie gewünscht. In ioBroker Adapter konfiguration habe ich dann die myVaillantApp Zugangsdaten hinterlegt und die Checkbox "myVaillant App verwenden" angewählt. Der Adapter kann sich auch verbinden und ist grün, allerdings ist im Log eine Fehlermeldung:

<html>
<body>

error | {"timestamp":"2023-12-15T16:39:32.122+00:00","status":404,"error":"Not Found","path":"/systems"}
-- | --

</body>
</html>

Ich habe auch die alten Objekte gelöscht um zu schauen was er dann anlegt. Es wird nur der Ordner 0 und in dem info angelegt sonst nichts.

Was kann ich tun damit es wieder funktioniert?

**Comment by TA2k** [comment]
mit der v0.2.0?

**Comment by JoeKN82** [comment]
habe ich übersehen das es auch schon die 0.2.0 gibt ich war noch auf der 0.1.2... mit der 0.2.0 funktioniert es wieder. vielen Danke

**Comment by JoeKN82** [comment]
damit mache ich es wieder zu.
